"use client";

/**
 * Hotel search hook (diagram: "Clients — Web" → API Gateway → Gemini
 * Service). Suggestions are generated by gemini-service
 * (POST /api/gemini/hotels/search) — the browser-side prompt + Gemini key
 * this hook used to carry is gone.
 *
 * The hook stays thin: it surfaces ApiClientError to the caller so each
 * component can render its own empty/error state (e.g. the search bar's
 * "No Results").
 */
import { getApiClient } from "@/lib/api";
import { Hotel } from "@/types/Hotel";

export const useHotels = () => {
  const getHotelQueryResult = async (query: string): Promise<Hotel[]> => {
    const { hotels } = await getApiClient().gemini.searchHotels({ query });
    // The shared HotelDto contract matches the app's Hotel type (image_url
    // included), so the results feed the store/cards unchanged.
    return hotels;
  };

  return { getHotelQueryResult };
};
